[CUMULUS] zebra: add static to mac table init
Warning seen because not marked as static function for
mac table init.

```
zebra/zebra_l2.c:245:6: error: no previous prototype for function 'zebra_init_mac_table' [-Werror,-Wmissing-prototypes]
void zebra_init_mac_table(struct zebra_l2_bridge_if *br)
     ^
zebra/zebra_l2.c:245:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
void zebra_init_mac_table(struct zebra_l2_bridge_if *br)
^
static
```

Signed-off-by: Stephen Worley <sworley@nvidia.com>