bgpd: [SOO] Fix warning workqueue header
work_queue_add is used in per src nhg code without including workqueue.h
Fix the warning

Before fix:
bgpd/bgp_per_src_nhg.c: In function 'bgp_per_src_nhg_peer_clear_route_cb':
bgpd/bgp_per_src_nhg.c:1982:41: warning: implicit declaration of function 'work_queue_add'; did you mean 'bpacket_queue_add'? [-Wimplicit-function-declaration]
 1982 |                                         work_queue_add(peer->clear_node_queue,
      |                                         ^~~~~~~~~~~~~~
      |                                         bpacket_queue_add

After fix:
Warning not seen

Ticket: #4156409
Signed-off-by: Karthikeya Venkat Muppalla <kmuppalla@nvidia.com>